version: '3.3'

services:
  db:
    image: postgres
    restart: always
    container_name: cobrando_db
    environment:
      - POSTGRES_USER=cobrando
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=cobrando_sas
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local